const Clothes = {
	Jacket: 'jacket',
	Coat: 'coat',
	Pants: 'pants',
	Shorts: 'Shorts',
	Scarf: 'scarf',
	Boots: 'boots',
	Sweatshirt: 'sheatshirt',
	Shirt: 'shirt',
	TShirt: 'tshirt',
	Sneakers: 'sneakers',
	Sandals: 'sandals',
	Hat: 'hat',
	Cap: 'cap',
	Scarf: 'scarf',
	Socks: 'socks',
	Glasses: 'glasses',
	Gloves: 'gloves',
	Hoodie: 'hoodie',
	Umbrella: 'umbrella',
	Sweater: 'sweater',
	WinterHat: 'winterhat',
	Shoe: 'shoe',
};

export default Clothes;